# Generated by Django 4.1.1 on 2023-09-27 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='log_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formapp.user'),
            preserve_default=False,
        ),
    ]
