# Generated by Django 4.1.1 on 2023-09-28 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_education_log_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='Course',
        ),
        migrations.RemoveField(
            model_name='education',
            name='University',
        ),
        migrations.RemoveField(
            model_name='education',
            name='date',
        ),
    ]
