# Generated by Django 4.1.1 on 2023-09-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0003_remove_education_course_remove_education_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='Course',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='University',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='date',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
